image: Visual Studio 2019

init:
  - git config --global core.autocrlf input
  
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - cmd: build.cmd

test: off

version: 0.0.1.{build}
